### ISSUE TITLE
Initial configuration test fails

### ISSUE THREAD

**Issue by zosocanuck** [qensus-labs/venafi-codesigning-wrapper-action#4]
I'm testing the following workflow on a GitHub hosted runner (ubuntu-latest):

```
name: qensus-csp-action-init-configuration
on:
  workflow_dispatch
  
jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}

    name: Example including initial configuration
    steps:
      - name: Setup CSPDriver
        uses: qensus-labs/venafi-codesigning-wrapper-action@v1.0.0
      - name: Check CSPDriver (version)
        run: pkcs11config --version
```

And getting this error:

```
Run qensus-labs/venafi-codesigning-wrapper-action@v1.0.0
  with:
    architecture: intel
    tpp-csc-url: https://localhost/csc
    tpp-version: [2](https://github.com/zosocanuck/sample-venafi-csp-pipeline/actions/runs/10080996162/job/27872055007#step:2:2)4.1.0
    include-config: false
    tpp-auth-url: https://localhost/vedauth
    tpp-hsm-url: https://localhost/vedhsm
    tpp-username: signer
Installing CSP Driver version 2[4](https://github.com/zosocanuck/sample-venafi-csp-pipeline/actions/runs/10080996162/job/27872055007#step:2:4).1.0...
Identified 'ubuntu' for Linux
/usr/bin/sudo apt show venaficodesign
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: No packages found
Error: The process '/usr/bin/sudo' failed with exit code [10](https://github.com/zosocanuck/sample-venafi-csp-pipeline/actions/runs/10080996162/job/27872055007#step:2:11)0
```
